### PR TITLE
fix stylus path

### LINKED ISSUE #11: Wrong path for app stylus file
@nekosaur On a fresh installation, the path of `app.styl` is wrong. Compilation then returns the following error:
```
This relative module was not found:
* ../node_modules/vuetify/src/stylus/app.styl in ./src/plugins/vuetify.js
```

Path must be changed to `'../../node_modules/vuetify/src/stylus/app.styl'` in `/generator/templates/default/src/plugins/vuetify.js` file.

### PR DESCRIPTION
**Pull request by andrewharvey**
closes #11

### CODE REVIEW

File: generator/templates/default/src/plugins/vuetify.js [hunk 1]
```diff
@@ -12,7 +12,7 @@ import {
   VToolbar,
   transitions
 } from 'vuetify'
-import '../node_modules/vuetify/src/stylus/app.styl'
+import '../..//node_modules/vuetify/src/stylus/app.styl'
```
Comment (nekosaur) [inline generator/templates/default/src/plugins/vuetify.js]: remove extra `/`

Comment (KaelWD) [reply generator/templates/default/src/plugins/vuetify.js]: Shouldn't this just be `'vuetify/src/stylus/app.styl'`? No idea why you guys like relative paths so much

**Comment by andrewharvey** [comment]
Whoops, fixed now. Agree with @KaelWD better to leave out the node_modules path, tested it without and seems fine.
